version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    command: [ "mongod", "--quiet", "--logpath", "/dev/null" ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/yourdatabase?authSource=admin"
      PORT: 4000
      FRONTEND_URL: "http://localhost:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: "npm run dev"

volumes:
  mongodb_data:
    driver: local
